### ISSUE TITLE
🍣 Thêm chi tiết các dịch vụ của CTMS

### ISSUE THREAD

**Issue by Belikhun** [Belikhun/ctms-plus#19]
## 🎈 góp ý tính năng
---
### 📃 Mô Tả
Mỗi dịch vụ trên CTMS đều có 1 bảng chi tiết ngắn gọn, đưa nội dung này vào CTMS+

### ✏ Nội Dung
Mỗi thẻ dịch vụ gồm có 2 nút **Thông Tin** và **MUA DỊCH VỤ**, khi nhấn vào nút **Thông Tin** sẽ hiện bảng chi tiết của dịch vụ đó

#### Thông tin thêm
![image](https://user-images.githubusercontent.com/19252372/120124466-c233b080-c1de-11eb-845d-88580167986b.png)

**Comment by belivipro9x99** [comment]
Issue này chưa được giải quyết vì vẫn còn thiếu 4 trang nữa

**Comment by kakashi250802** [comment]
let make it

**Comment by Belikhun** [comment]
Issue stalled. Closing this for now
