### ISSUE TITLE
📅 Thêm tính năng xem lịch học khi hết hạn CTMS

### ISSUE THREAD

**Issue by nc-minh** [Belikhun/ctms-plus#51]
## 🎈 góp ý tính năng
---
### 📃 Mô Tả
Khi hết hạn ctms sẽ không xem được lịch học nữa, nhưng trong ctms có một cái lịch học public luôn mở miễn phí, trong mỗi mỗi môn học chúng ta đều có mã môn học, có thể dùng mã này so sánh với mã được public của ctms để dựng lại khung lịch học cho 1 tài khoản, nhưng yêu cầu tài khoản đó cần biết rõ mình học lớp nào với mã môn là gì, nếu không nhớ chúng ta có thể xem mã môn đó trên hệ thống lms nếu đang học online.

### 📃 Ý tưởng
Anh không tìm thấy api trả về mà nó trả ra cả trang có nội dung luôn ở http://ctms.fithou.net.vn/index.aspx không cần đăng nhập cũng xem được. Có thể dùng cách lọc thông tin từng buổi học qua thẻ ```<table class="smallfont">``` rồi chuyển về dạng json để mình đọc ra từ giao diện của mình theo mã môn mà các bạn muốn xem cấu hình từ ban đầu :>> 💯 
-- Anh nghĩ thế thôi không biết khi triển khai sẽ như nào 🤣  🤣  🤣

**Comment by Belikhun** [comment]
Tính năng này sẽ được di chuyển tới một screen mới là **`screen:home`** thay vì mở rộng **`screen:schedule`** vì tính phức tạp của nó. Screen này sẽ có 2 tab gồm tab xem lịch học của toàn khoa và tab xem lịch học riêng của người dùng hiện tại. Danh sách mã lớp của người dùng hiện tại sẽ được tự động update nếu **`api:subscribe`** được gọi hoặc có thể update bằng tay nếu người dùng đã có danh sách mã lớp. API mới **`api:home`** cũng sẽ được thêm để phục vụ cho tính năng này,
