### ISSUE TITLE
Error Handler Xếp Nhóm trong Kết Quả Học Tập

### ISSUE THREAD

**Issue by nicejjss** [Belikhun/ctms-plus#67]
## 🐞 báo cáo lỗi Xếp nhóm các môn trong kì học 
---
### 📃 Mô Tả

xuất hiện ERROR OCCURED
Một lỗi không mong muốn đã sảy ra!
Phiên làm việc hết hạn

### 🔬 Cách Gây Ra Lỗi
1. Đi tới 'Kết Quả Học Tập'
2. Nhấn vào 'Xếp nhóm'
4. Lỗi!!!

### 🌍 Phiên Bản
 - Hệ điều hành: Windows
 - Trình duyệt: Edge

**Comment by Belikhun** [comment]
Lỗi này có thể là do trang lịch học chưa được tải hoàn thiện để lấy thông tin state nên khi tải lịch học của ngày khác trang sẽ báo lỗi phiên hết hạn. Lỗi này khá đơn giản nên mình sẽ fix nhanh nên bạn chờ một lúc nhé.

**Comment by Belikhun** [comment]
Mình đã fix xong tại pull request #68. Sẽ mất tầm 1-2p để có hiệu lực tới production. Bạn test lại xem còn lỗi ko nha 🥰
