### ISSUE TITLE
Tài khoản CTMS4KINHTE không thể đăng nhập được trên CTMS+

### ISSUE THREAD

**Issue by lemanhjcuongdev** [Belikhun/ctms-plus#69]
## 🐞 báo cáo lỗi
---
### 📃 Mô Tả
CTMS Plus hiện chỉ đăng nhập vào được với tài khoản của khoa F, nhưng độ nổi tiếng của CTMS Plus đã lan sang khoa Kinh tế, nên các bạn đang có nguyện vọng muốn được đăng nhập bằng tài khoản của khoa Kinh Tế vào hệ thống của CTMS Plus

### 🔬 Cách Gây Ra Lỗi
1. Đi tới 'CTMS Plus'
2. Nhấn vào 'Đăng nhập'
3. Sử dụng tài khoản của khoa Kinh Tế
4. Lỗi sai tài khoản và mật khẩu!!!

### 🎯 Hành Vi Dự Kiến
Khoa kinh tế cũng có thể đăng nhập vào được

#### Thông tin thêm
Cảm ơn Belikhun đã đọc đến đây, tôi và các bạn sinh viên khoa Kinh Tế cảm ơn dự án tuyệt vời này của bạn! Good day✨!

**Comment by Belikhun** [comment]
Do mình không có tài khoản ctms của khoa kinh tế nên mình không thể test được). Nếu bạn sẵn lòng cho mình mượn tài khoản ctms của bạn thì hãy PM mình qua discord `Belikhun#4688` hoặc qua [messenger](https://www.messenger.com/t/100006097004070) nhé 🥰.
